; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32

; Global settings inherited AUTOMATICALLY by every [env:NAME] block
[env]
platform =
	platformio/espressif32@7.0.1
lib_deps =
	M5PM1@1.0.6
	M5GFX@0.2.19
framework = espidf
upload_speed = 115200
monitor_speed = 115200
lib_compat_mode = off
board_build.filesystem = littlefs
board_build.partitions = partitions_4m.csv
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults.common"
extra_scripts = 
	pre:scripts/gen_version.py
	pre:scripts/gen_assets.py
	pre:scripts/gen_tft_setup.py
board_build.embed_txtfiles = 
	defaults/config.json    # defaults/config.json (readable JSON source)
	defaults/timezones.json # defaults/timezones.json (readable JSON source)
	defaults/presets.json   # defaults/presets.json (readable JSON source)
	.pio/.version           # .version (readable version string)
	dist/index.html         # dist/index.html (minified HTML source)
	dist/index.js.gz        # dist/index.js (minified JS source)
	dist/style.css.gz       # dist/style.css (minified CSS source)
build_flags = 
	-DFASTLED_INTERRUPT_RETRY_COUNT=0
	-DCORE_DEBUG_LEVEL=0
	-DSERIAL_BAUD=115200
	-DESP32
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os

; Shared debug base profile (Does not begin with env:)
[debug_common]
build_type = debug
build_unflags = -DLOG_LOCAL_LEVEL
build_flags = 
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS="sdkconfig.defaults.common;sdkconfig.defaults.debug"

; ==========================================
; ESP32 STANDARD DEV KIT
; ==========================================
[env:esp32]
board = esp32dev
build_flags = ${env.build_flags} -DOTA_ENV=esp32

[env:esp32_debug]
extends = env:esp32, debug_common
build_flags = ${env:esp32.build_flags} ${debug_common.build_flags}

; ==========================================
; ESP32 DEVKIT V1
; ==========================================
[env:esp32d]
board = esp32doit-devkit-v1
build_flags = ${env.build_flags} -DOTA_ENV=esp32d

[env:esp32d_debug]
extends = env:esp32d, debug_common
build_flags = ${env:esp32d.build_flags} ${debug_common.build_flags}

; ==========================================
; ESP32-C3
; ==========================================
[env:esp32c3]
board = esp32-c3-devkitm-1
build_flags = ${env.build_flags} -DOTA_ENV=esp32c3

[env:esp32c3_debug]
extends = env:esp32c3, debug_common
build_flags = ${env:esp32c3.build_flags} ${debug_common.build_flags}

; ==========================================
; ESP32-S3 (Overrides 4MB settings to 8MB)
; ==========================================
[env:esp32s3]
board = esp32-s3-devkitc-1
board_build.partitions = partitions_8m.csv
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.cmake_extra_args =
	-DSDKCONFIG_DEFAULTS="sdkconfig.defaults.common;sdkconfig.defaults.8mb"

[env:esp32s3_debug]
extends = env:esp32s3, debug_common
build_flags = ${env:esp32s3.build_flags} ${debug_common.build_flags}
board_build.cmake_extra_args =
	-DSDKCONFIG_DEFAULTS="sdkconfig.defaults.common;sdkconfig.defaults.8mb;sdkconfig.defaults.debug"

; ==========================================
; ESP32-C6
; ==========================================
[env:esp32c6]
board = esp32-c6-devkitc-1
build_flags = ${env.build_flags} -DOTA_ENV=esp32c6

[env:esp32c6_debug]
extends = env:esp32c6, debug_common
build_flags = ${env:esp32c6.build_flags} ${debug_common.build_flags}
