; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32d

[common]
platform = espressif32@7.0.1
framework = espidf
upload_speed = 115200
monitor_speed = 115200
board_build.esp-idf.sdkconfig_path = sdkconfig
board_build.filesystem = littlefs
board_build.partitions = partitions_4m.csv
extra_scripts = 
	pre:scripts/gen_version.py
	pre:scripts/embed_assets.py
	pre:scripts/link_user_setup.py
	pre:scripts/clean_inc_folder.py
lib_deps = 
build_flags = 
	-DFASTLED_INTERRUPT_RETRY_COUNT=0
	-DCORE_DEBUG_LEVEL=0
	-DSERIAL_BAUD=115200
	-Os

[env:esp32]
platform = ${common.platform}
board = esp32dev
framework = ${common.framework}
lib_compat_mode = off
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DESP32
	-DOTA_ENV=esp32
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32_debug]
extends = esp32
platform = ${env:esp32.platform}
board = ${env:esp32.board}
framework = ${env:esp32.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32.lib_deps}
build_flags =
	${env:esp32.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb.debug
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32d]
platform = ${common.platform}
board = esp32doit-devkit-v1
framework = ${common.framework}
lib_compat_mode = off
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DESP32
	-DOTA_ENV=esp32d
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = partitions_4m.csv
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32d_debug]
extends = esp32d
platform = ${env:esp32d.platform}
board = ${env:esp32d.board}
framework = ${env:esp32d.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32d.lib_deps}
build_flags =
	${env:esp32d.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = partitions_4m.csv
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb.debug
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32c3]
platform = ${common.platform}
board = esp32-c3-devkitm-1
framework = ${common.framework}
lib_compat_mode = off
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DESP32
	-DOTA_ENV=esp32c3
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32c3_debug]
extends = esp32c3
platform = ${env:esp32c3.platform}
board = ${env:esp32c3.board}
framework = ${env:esp32c3.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32c3.lib_deps}
build_flags =
	${env:esp32c3.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb.debug
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32s3]
platform = ${common.platform}
board = esp32-s3-devkitc-1
framework = ${common.framework}
lib_compat_mode = off
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DESP32
	-DOTA_ENV=esp32s3
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = partitions_8m.csv
board_build.flash_size = 8MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.8mb
board_upload.flash_size = 8MB
extra_scripts = ${common.extra_scripts}

[env:esp32s3_debug]
extends = esp32s3
platform = ${env:esp32s3.platform}
board = ${env:esp32s3.board}
framework = ${env:esp32s3.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32s3.lib_deps}
build_flags =
	${env:esp32s3.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = partitions_8m.csv
board_build.flash_size = 8MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.8mb.debug
board_upload.flash_size = 8MB
extra_scripts = ${common.extra_scripts}

[env:esp32c6]
platform = ${common.platform}
board = esp32-c6-devkitc-1
framework = ${common.framework}
lib_compat_mode = off
build_flags =
	-DCORE_DEBUG_LEVEL=0
	-DESP32
	-DOTA_ENV=esp32c6
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32c6_debug]
extends = esp32c6
platform = ${env:esp32c6.platform}
board = ${env:esp32c6.board}
framework = ${env:esp32c6.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32c6.lib_deps}
build_flags =
	${env:esp32c6.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_build.cmake_extra_args = -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.4mb.debug
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}
