; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32d

[common]
platform = espressif32@6.12.0
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
minify = true
extra_scripts = 
	pre:scripts/gen_version.py
	pre:scripts/embed_assets.py
	pre:scripts/link_user_setup.py
	pre:scripts/clean_inc_folder.py
build_flags = 
	-DFASTLED_ESP8266_RAW_PIN_ORDER
	-DFASTLED_INTERRUPT_RETRY_COUNT=0
	-DARDUINOJSON_USE_LONG_LONG=1
	-DCORE_DEBUG_LEVEL=5
	-DSERIAL_BAUD=115200
	-Os

[env:esp32d]
platform = ${common.platform}
board = esp32doit-devkit-v1
framework = ${common.framework}
lib_deps =
	AsyncTCP
	bblanchon/ArduinoJson@^6.21.3
	makuna/NeoPixelBus@^2.8.4
build_src_filter = +<*> -<SPIStub.cpp>
build_flags =
	${common.build_flags}
	-DOTA_ENV=\"esp32d\"
	-DARDUINOJSON_ENABLE_ARDUINO_STRING=0
	-DARDUINOJSON_ENABLE_ARDUINO_STREAM=0
	-DARDUINOJSON_ENABLE_PROGMEM=0
	-fpermissive
monitor_speed = ${common.monitor_speed}
extra_scripts = ${common.extra_scripts}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}

[env:esp32d_debug]
extends = esp32d
platform = ${common.platform}
board = ${env:esp32d.board}
framework = ${common.framework}
lib_deps =
	${env:esp32d.lib_deps}
build_src_filter = +<*> -<SPIStub.cpp>
build_flags =
	${env:esp32d.build_flags}
	-DDEBUG_SERIAL
	-g
	-O0
monitor_speed = ${common.monitor_speed}
extra_scripts = ${common.extra_scripts}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}

[env:esp32c6]
platform = ${common.platform}
board = esp32-c6-devkitc-1
framework = espidf
lib_compat_mode = off
lib_deps =
	bblanchon/ArduinoJson@^6.21.3
build_flags =
	-DARDUINOJSON_USE_LONG_LONG=1
	-DESP32
	-DOTA_ENV=\"esp32c6\"
	-DARDUINO_ARCH_ESP32
	-I${PROJECTSRC_DIR}
	-Os
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}

[env:esp32c6_debug]
extends = esp32c6
platform = ${env:esp32c6.platform}
board = ${env:esp32c6.board}
framework = ${env:esp32c6.framework}
lib_compat_mode = off
lib_deps =
	${env:esp32c6.lib_deps}
build_flags =
	${env:esp32c6.build_flags}
	-DDEBUG_SERIAL
	-DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
monitor_speed = ${common.monitor_speed}
board_build.filesystem = littlefs
board_build.partitions = ${common.board_build.partitions}
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
extra_scripts = ${common.extra_scripts}
