# PlatformIO Project Configuration Override for Aquarium Controller
# This file enables the Aquarium Controller usermod

[platformio]
default_envs = Athom_4Pin_Controller

[env:Athom_4Pin_Controller]       ; With clock and data interface
board = esp8285
platform = ${common.platform_wled_default}
platform_packages = ${common.platform_packages}
board_build.ldscript = ${common.ldscript_2m512k}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp8266.build_flags}
  -D WLED_RELEASE_NAME=\"Athom_4Pin_Controller\"
  -D BTNPIN=0
  -D RLYPIN=12
  -D LEDPIN=1
  -D WLED_DISABLE_INFRARED
  -D WLED_DISABLE_PARTICLESYSTEM1D
  -D WLED_DISABLE_PARTICLESYSTEM2D
  -D USERMOD_AQUARIUM_CONTROLLER
  -D USERMOD_ID_AQUARIUM_CONTROLLER=59
custom_usermods = aquarium_controller
lib_deps = ${esp8266.lib_deps}

[env:Athom_4Pin_Controller_debug] ; Debug version of Athom_4Pin_Controller
extends = env:Athom_4Pin_Controller
build_flags =
  ${env:Athom_4Pin_Controller.build_flags}
  -D WLED_DEBUG
